version: "3"

services:
  mongodb:
    image: mongo:latest
    command: mongod --port 27018
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=34SY_H34LTH_TWO
    ports:
      - "27018:27018"
    volumes:
      - ./volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
